site_name: crisp-t
repo_url: https://github.com/dermatologist/crisp-t
site_url: https://dermatologist.github.io/crisp-t
site_description: Qualitative Research support tools in Python!
site_author: Bell Eapen
edit_uri: edit/main/docs/
repo_name: dermatologist/crisp-t
copyright: Maintained by <a href="https://dermatologist.com">dermatologist</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/crisp_t"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dermatologist/crisp-t
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/crisp-t

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
