name: Python Test

on:
  schedule:
    - cron: '1 1 2,16 * *'  # every 2nd and 16th at 01:01. To flag any dependency issues.
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop
      - main

jobs:
  build:
    timeout-minutes: 15
    strategy:
      max-parallel: 4
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5

    - name: Set up the environment
      uses: ./.github/actions/setup-python-env

    - name: Run tests
      run: uv run python -m pytest tests --cov --cov-config=pyproject.toml --cov-report=xml

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Check if documentation can be built
        run: uv run mkdocs build